# .github/workflows/kernel-build.yml
#
# Phase-1  → cross-arch HWE-6.11 kernel build & packaging
# Phase-2  → perf-tuned .config + hackbench (rt-tests) regression gate

name: "CI: Kernel Build & Bench"

on:
  push:
  pull_request:

concurrency:
  group: "kernel-${{ github.ref }}-${{ github.sha }}"
  cancel-in-progress: false

env:
  DEBIAN_FRONTEND: noninteractive
  ASIOS_CLEANUP: "1"          # keep trees until we clean explicitly
  USE_DISTRO_CONFIG: "1"      # start from stock HWE .config
  COSIGN_VERSION: "v2.0.0"
  KVER: "6.11"

# ─────────────────────────────────────────────────────────────────────
# BUILD – cross-compile *both* arches once, package & upload
# ─────────────────────────────────────────────────────────────────────
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            build-essential bc flex bison libssl-dev libelf-dev dwarves \
            liblz4-dev libzstd-dev libbz2-dev liblzma-dev \
            crossbuild-essential-arm64 crossbuild-essential-amd64 \
            qemu-user-static debhelper-compat fakeroot curl

      - name: Install cosign ${{ env.COSIGN_VERSION }}
        run: |
          ARCH=$(dpkg --print-architecture)
          BIN="cosign-linux-${ARCH/amd64/amd64}"
          curl -sSL -o cosign \
            "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/${BIN}"
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Inject module-signing key
        run: |
          mkdir -p scripts/common/certs
          printf '%s\n' "${{ secrets.ASIOS_SIGNING_KEY }}" \
            > scripts/common/certs/asios-signing.pem
          chmod 600 scripts/common/certs/asios-signing.pem

      - name: Cross-compile ASIOS kernels (x86_64 + arm64)
        run: scripts/common/build-asios-kernel.sh


