# .github/workflows/kernel-build.yml

name: "CI: Kernel Build"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc flex bison libssl-dev libelf-dev dwarves \
            liblz4-dev libzstd-dev libbz2-dev liblzma-dev \
            crossbuild-essential-arm64 crossbuild-essential-amd64 qemu-user-static \
            debhelper-compat fakeroot

      - name: Build ASIOS kernel
        run: scripts/common/build-asios-kernel.sh --host-only

      - name: Package kernel (x86_64)
        if: ${{ matrix.arch == 'x86_64' }}
        run: scripts/x86_64/build-deb.sh

      - name: Package kernel (ARM64)
        if: ${{ matrix.arch == 'aarch64' }}
        run: scripts/arm64/build-deb.sh

      - name: Run smoke tests
        run: |
          pushd output-debs
          bash ../tests/test-*.sh
          popd
