# .github/workflows/kernel-build.yml

name: "CI: Kernel Build"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc flex bison libssl-dev libelf-dev dwarves \
            liblz4-dev libzstd-dev libbz2-dev liblzma-dev \
            crossbuild-essential-arm64 crossbuild-essential-amd64 qemu-user-static \
            debhelper-compat fakeroot

      - name: Inject signing key
        run: |
          mkdir -p scripts/common/certs
          echo "${{ secrets.ASIOS_SIGNING_KEY }}" > scripts/common/certs/asios-signing.pem
          chmod 600 scripts/common/certs/asios-signing.pem

      - name: Build ASIOS kernel (both arches)
        env:
          USE_DISTRO_CONFIG: "1"
          ASIOS_CLEANUP:    "0"
        run: scripts/common/build-asios-kernel.sh

      - name: Prepare packaging build trees
        run: |
          # copy host build tree into arch-specific folder
          mkdir -p scripts/x86_64/x86_64_build scripts/arm64/arm64_build
          cp -r scripts/common/x86_64_build/kernel-build-6.11 scripts/x86_64/x86_64_build/
          cp -r scripts/common/arm64_build/kernel-build-6.11  scripts/arm64/arm64_build/

      - name: Package kernel (x86_64)
        if: ${{ matrix.arch == 'x86_64' }}
        run: scripts/x86_64/build-deb.sh

      - name: Package kernel (ARM64)
        if: ${{ matrix.arch == 'aarch64' }}
        run: scripts/arm64/build-deb.sh

      - name: Run smoke tests
        run: |
          pushd output-debs
          bash ../tests/test-*.sh
          popd

      - name: Upload built .deb packages
        uses: actions/upload-artifact@v4
        with:
          name: asios-debs-${{ matrix.arch }}
          path: output-debs/*.deb
          retention-days: 7
